### ISSUE TITLE
SyntaxError: invalid syntax` File "/code/code2vec/vocabularies.py", line 45

### ISSUE THREAD

**Issue by jeroenherczeg** [tech-srl/code2vec#31]
When I try to run the training with tf2.0 in docker with gpu support, I get the following error:

```docker run --runtime=nvidia -it -v $(realpath ~/Code):/code -u $(id -u):$(id -g) tensorflow/tensorflow:2.0.0a0-gpu-py3 bash```

```tf-docker /code/code2vec > source train.sh 
]Traceback (most recent call last):
  File "code2vec.py", line 1, in <module>
    from vocabularies import VocabType
  File "/code/code2vec/vocabularies.py", line 45
    self.word_to_index: Dict[str, int] = {}
                      ^
SyntaxError: invalid syntax```

**Comment by urialon** [comment]
Hi,
Sorry for the inconveniences.
@eladn - can you check what's wrong with these type annotations?

**Comment by eladn** [comment]
Hi. What python version do you use?

**Comment by jeroenherczeg** [comment]
Thanks guys for looking into this!
```
tf-docker / > python --version
Python 3.5.2

tf-docker / > pip list
Package              Version
-------------------- ----------------------
absl-py              0.7.0
astor                0.7.1
gast                 0.2.2
google-pasta         0.1.4
grpcio               1.19.0
h5py                 2.9.0
Keras-Applications   1.0.7
Keras-Preprocessing  1.0.9
Markdown             3.0.1
numpy                1.16.2
pip                  19.0.3
protobuf             3.7.0
pycurl               7.43.0
pygobject            3.20.0
python-apt           1.1.0b1+ubuntu0.16.4.2
setuptools           40.8.0
six                  1.12.0
tb-nightly           1.14.0a20190301
tensorflow-gpu       2.0.0a0
termcolor            1.1.0
tf-estimator-nightly 1.14.0.dev2019030115
Werkzeug             0.14.1
wheel                0.29.0

**Comment by urialon** [comment]
Hi Jeroen,
I discussed it with @eladn -
As far as I know, type annotations were introduced in Python 3.6, so they won't work with 3.5.

- If you can - upgrade to python 3.7, which is the latest version that @eladn had checked it with.

- If you can't or don't want to update the python version, you can `checkout` commit `9789cfa0d7ee74b8dca9e2b84c45228b86716d1c` which did not contain type annotations and is supposed to work with python3.5.

Please let us know how it goes

**Comment by jeroenherczeg** [comment]
Thanks!

I saw there was an updated tensorflow docker container (tensorflow/tensorflow:2.0.0b1-gpu-py3), which uses Python 3.6.8 and this indeed fixes the problem!

:1st_place_medal:

**Comment by jeroenherczeg** [comment]
Just to be complete, I tried checking out commit 9789cfa0d7ee74b8dca9e2b84c45228b86716d1c, and run it, but got:

```Traceback (most recent call last):
  File "code2vec.py", line 37, in <module>
    model = Model(config)
  File "/code/code2vec/model.py", line 16, in __init__
    self.sess = tf.Session()
AttributeError: module 'tensorflow' has no attribute 'Session'```

Anyway 3.6 works!
